<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>import AdminShell from '../../components/AdminShell.vue';import StatusBadge from '../../components/StatusBadge.vue';import {receivables,payables,cashflow,budgets} from '../../api/mock';const bars=[64,78,70,86,77,93,82,98,84,100,89,96]</script>
<template><AdminShell><template #title>财务驾驶舱</template>
  <div class="page-heading"><div><p>FINANCE OVERVIEW</p><h1>财务驾驶舱</h1><span>资金、往来与预算执行的统一经营视图</span></div><div><button class="button secondary">导出月报</button><button class="button primary">＋ 新建财务事项</button></div></div>
  <section class="metric-grid five"><article><header><span>可用资金</span><i>￥</i></header><strong>425.01<small> 万</small></strong><p><b>↑ 8.6%</b> 较月初</p></article><article><header><span>应收余额</span><i>收</i></header><strong>199.40<small> 万</small></strong><p>其中逾期 <b>23.80 万</b></p></article><article><header><span>应付余额</span><i>付</i></header><strong>33.01<small> 万</small></strong><p>7 日内到期 23.55 万</p></article><article><header><span>预算执行率</span><i>算</i></header><strong>58.4<small> %</small></strong><p>符合年度执行节奏</p></article><article class="warning"><header><span>待审费用</span><i>审</i></header><strong>4<small> 笔</small></strong><p><b>1 笔</b> 已等待超过 24h</p></article></section>
  <section class="dashboard-grid"><div class="card cash-trend"><header><div><h2>现金流趋势</h2><p>近 12 个月现金流入、流出与净额</p></div><div class="legend"><span><i></i>流入</span><span><i></i>流出</span></div></header><div class="chart-area"><div class="chart-scale"><span>240</span><span>180</span><span>120</span><span>60</span><span>0</span></div><div class="bar-chart"><div v-for="(v,i) in cashflow" :key="i" class="bar-group"><div><i :style="{height:v/2.3+'px'}"></i><em :style="{height:bars[i]/2.3+'px'}"></em></div><small>{{i+1}}月</small></div></div></div><footer><div><span>本年累计流入</span><b>1,769.0 万</b></div><div><span>本年累计流出</span><b>1,192.6 万</b></div><div><span>经营净现金流</span><b class="positive">+576.4 万</b></div></footer></div>
  <div class="card action-center"><header><div><h2>今日资金安排</h2><p>按到期日与风险优先级排序</p></div><em>查看日历 →</em></header><article><time>09:30</time><i class="dot red"></i><div><b>云资源采购付款</b><small>上海云舟科技 · 18.65 万</small></div><StatusBadge value="待复核"/></article><article><time>11:00</time><i class="dot amber"></i><div><b>澄川智能回款确认</b><small>项目进度款 · 36.00 万</small></div><StatusBadge value="跟进中"/></article><article><time>14:30</time><i class="dot teal"></i><div><b>7 月费用批次付款</b><small>18 笔 · 6.82 万</small></div><StatusBadge value="已排程"/></article><article><time>16:00</time><i class="dot navy"></i><div><b>银企账户日终对账</b><small>4 个账户 · 自动对账</small></div><StatusBadge value="未开始"/></article><footer>预计日终可用余额 <b>402.18 万</b></footer></div></section>
  <section class="dashboard-bottom"><div class="card"><header><div><h2>重点应收</h2><p>客户回款与账龄跟踪</p></div><em>全部应收 →</em></header><table><thead><tr><th>客户 / 单据</th><th>到期</th><th>未收金额</th><th>状态</th></tr></thead><tbody><tr v-for="x in receivables.slice(0,4)" :key="x.no"><td><b>{{x.customer}}</b><small>{{x.no}}</small></td><td :class="{'danger-text':x.status==='已逾期'}">{{x.due}}</td><td><b>{{(x.amount-x.received).toFixed(2)}} 万</b></td><td><StatusBadge :value="x.status"/></td></tr></tbody></table></div>
  <div class="card budget-brief"><header><div><h2>预算执行</h2><p>年度预算按责任中心</p></div><em>预算中心 →</em></header><article v-for="x in budgets.slice(0,4)" :key="x.dept"><div><b>{{x.dept}}</b><small>{{x.subject}} · {{x.actual}} / {{x.annual}} 万</small></div><strong>{{x.rate}}%</strong><span><i :class="{warn:x.status==='预警'}" :style="{width:x.rate+'%'}"></i></span></article></div>
  <div class="card"><header><div><h2>付款计划</h2><p>未来 14 天待付款项</p></div><em>全部应付 →</em></header><div class="payment-list"><article v-for="x in payables" :key="x.no"><time><b>{{x.due.split('-')[1]}}</b><small>08 月</small></time><div><b>{{x.supplier}}</b><small>{{x.source}}</small></div><strong>{{(x.amount-x.paid).toFixed(2)}} 万</strong></article></div></div></section>
</AdminShell></template>
