-- Copyright 2026 上海如静知华信息科技有限公司
CREATE TABLE sys_user (id BIGINT PRIMARY KEY AUTO_INCREMENT,username VARCHAR(40) NOT NULL UNIQUE,password VARCHAR(100) NOT NULL,display_name VARCHAR(40) NOT NULL,role VARCHAR(20) NOT NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE fms_cash_account (id BIGINT PRIMARY KEY AUTO_INCREMENT,account_code VARCHAR(32) NOT NULL UNIQUE,account_name VARCHAR(80) NOT NULL,bank_name VARCHAR(80) NOT NULL,account_type VARCHAR(40) NOT NULL,balance DECIMAL(16,2) NOT NULL,available_balance DECIMAL(16,2) NOT NULL,currency VARCHAR(16) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE fms_receivable (id BIGINT PRIMARY KEY AUTO_INCREMENT,receivable_no VARCHAR(32) NOT NULL UNIQUE,customer_name VARCHAR(100) NOT NULL,source_document VARCHAR(100) NOT NULL,amount DECIMAL(16,2) NOT NULL,received_amount DECIMAL(16,2) NOT NULL,due_date DATE NOT NULL,owner VARCHAR(40) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE fms_payable (id BIGINT PRIMARY KEY AUTO_INCREMENT,payable_no VARCHAR(32) NOT NULL UNIQUE,supplier_name VARCHAR(100) NOT NULL,source_document VARCHAR(100) NOT NULL,amount DECIMAL(16,2) NOT NULL,paid_amount DECIMAL(16,2) NOT NULL,due_date DATE NOT NULL,applicant VARCHAR(40) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE fms_expense_claim (id BIGINT PRIMARY KEY AUTO_INCREMENT,claim_no VARCHAR(32) NOT NULL UNIQUE,claimant VARCHAR(40) NOT NULL,department VARCHAR(60) NOT NULL,category VARCHAR(40) NOT NULL,purpose VARCHAR(160) NOT NULL,amount DECIMAL(14,2) NOT NULL,expense_date DATE NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE fms_budget (id BIGINT PRIMARY KEY AUTO_INCREMENT,budget_no VARCHAR(32) NOT NULL UNIQUE,department VARCHAR(60) NOT NULL,subject_name VARCHAR(60) NOT NULL,fiscal_year INT NOT NULL,annual_amount DECIMAL(16,2) NOT NULL,occupied_amount DECIMAL(16,2) NOT NULL,actual_amount DECIMAL(16,2) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE INDEX idx_fms_receivable_due ON fms_receivable(due_date,status);
CREATE INDEX idx_fms_payable_due ON fms_payable(due_date,status);
CREATE INDEX idx_fms_expense_status ON fms_expense_claim(status,expense_date);
CREATE INDEX idx_fms_budget_year_dept ON fms_budget(fiscal_year,department);
